//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SolutionValidator.UI.Console.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SolutionValidator.UI.Console.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionValidator started..
        /// </summary>
        internal static string Program_Main_SolutionValidator_started {
            get {
                return ResourceManager.GetString("Program_Main_SolutionValidator_started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file: &gt;{0}&lt; does not exist..
        /// </summary>
        internal static string Program_Run_Configuration_file_does_not_exist {
            get {
                return ResourceManager.GetString("Program_Run_Configuration_file_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        internal static string Program_Run_Error {
            get {
                return ResourceManager.GetString("Program_Run_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error when processing Repository root path: &gt;{0}&lt;..
        /// </summary>
        internal static string Program_Run_Error_when_processing_Repository_root_path {
            get {
                return ResourceManager.GetString("Program_Run_Error_when_processing_Repository_root_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed: {0}.
        /// </summary>
        internal static string Program_Run_Passed {
            get {
                return ResourceManager.GetString("Program_Run_Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue . . ..
        /// </summary>
        internal static string Program_Run_Press_any_key_to_continue {
            get {
                return ResourceManager.GetString("Program_Run_Press_any_key_to_continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository root path &gt;{0}&lt; does not exist..
        /// </summary>
        internal static string Program_Run_Repository_root_path__does_not_exist {
            get {
                return ResourceManager.GetString("Program_Run_Repository_root_path__does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SolutionValidator exited with code {0}..
        /// </summary>
        internal static string Program_Run_SolutionValidator_exited_with_code {
            get {
                return ResourceManager.GetString("Program_Run_SolutionValidator_exited_with_code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total checks: {0}. Total errors found: {1}.
        /// </summary>
        internal static string Program_Run_Total_checks_Total_errors_found {
            get {
                return ResourceManager.GetString("Program_Run_Total_checks_Total_errors_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error: {0}.
        /// </summary>
        internal static string Program_Run_Unexpected_error {
            get {
                return ResourceManager.GetString("Program_Run_Unexpected_error", resourceCulture);
            }
        }
    }
}
